export const VIRTUAL_ROOT_VALUE = "__virtual_root__";
export const CACHED_FILES_STORAGE_KEY = "xsd-viewer:cached-files";
export const SELECTED_ROOT_STORAGE_KEY = "xsd-viewer:selected-root";

export const BUILT_IN_TYPES = new Set([
  "anyuri",
  "base64binary",
  "boolean",
  "byte",
  "date",
  "datetime",
  "decimal",
  "double",
  "duration",
  "float",
  "gday",
  "gmonth",
  "gmonthday",
  "gyear",
  "gyearmonth",
  "hexbinary",
  "int",
  "integer",
  "long",
  "name",
  "ncname",
  "negativeinteger",
  "nmtoken",
  "nonnegativeinteger",
  "nonpositiveinteger",
  "normalizedstring",
  "positiveinteger",
  "qname",
  "short",
  "string",
  "time",
  "token",
  "unsignedbyte",
  "unsignedint",
  "unsignedlong",
  "unsignedshort",
]);
